# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wechat_django', '0004_templatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatPay',
            fields=[
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pay', serialize=False, to='wechat_django.WeChatApp')),
                ('mch_id', models.CharField(help_text='微信支付分配的商户号', max_length=32, verbose_name='mch_id')),
                ('api_key', models.CharField(help_text='商户号key', max_length=128, verbose_name='WeChatPay api_key')),
                ('sub_mch_id', models.CharField(blank=True, help_text='子商户号，受理模式下填写', max_length=32, null=True, verbose_name='sub_mch_id')),
                ('mch_app_id', models.CharField(blank=True, help_text='微信分配的公众账号ID，受理模式下填写', max_length=32, null=True, verbose_name='mch_app_id')),
                ('mch_cert', models.BinaryField(blank=True, null=True, verbose_name='mch_cert')),
                ('mch_key', models.BinaryField(blank=True, null=True, verbose_name='mch_key')),
            ],
            options={
                'verbose_name_plural': 'WeChat pay',
                'verbose_name': 'WeChat pay',
            },
        ),
    ]
