# -*- coding: utf-8 -*-
# Generated by Django 3.0 on 2019-12-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wechat_django', '0006_app_parent'),
        ('wechat_django_pay', '0001_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPartnerApp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': []
            },
            bases=('wechat_django.wechatapp',),
        ),
        migrations.CreateModel(
            name='WeChatSubPay',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': []
            },
            bases=('wechat_django_pay.wechatpay',),
        ),
        migrations.RemoveField(
            model_name='wechatpay',
            name='mch_app_id',
        ),
        migrations.RemoveField(
            model_name='wechatpay',
            name='sub_mch_id',
        ),
        migrations.AddField(
            model_name='wechatpay',
            name='sub_appid',
            field=models.CharField(blank=True, help_text='微信分配的子商户公众账号ID,受理模式下填写', max_length=32, null=True, verbose_name='sub_appid'),
        ),
        migrations.RenameField(
            model_name='wechatpay',
            old_name='mch_id',
            new_name='_mch_id',
        ),
        migrations.AlterField(
            model_name='wechatpay',
            name='_mch_id',
            field=models.CharField(help_text='微信支付分配的商户号,若为服务商,则为子商户号', max_length=32, verbose_name='mch_id'),
        ),
        migrations.AlterField(
            model_name='wechatpay',
            name='_mch_id',
            field=models.CharField(db_column='mch_id', help_text='微信支付分配的商户号,若为服务商,则为子商户号', max_length=32, verbose_name='mch_id'),
        ),
        migrations.AddField(
            model_name='wechatpay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='wechatpay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
