# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('menuid', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=20)),
                ('content', jsonfield.fields.JSONField()),
                ('ext_info', jsonfield.fields.JSONField()),
                ('weight', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('src', models.PositiveSmallIntegerField(choices=[(0, 'wechat'), (2, 'self'), (1, 'menu')], default=2)),
                ('strategy', models.CharField(choices=[('reply_all', 'reply_all'), ('random_one', 'random_one')], max_length=10)),
                ('starts', models.DateTimeField(blank=True, null=True)),
                ('ends', models.DateTimeField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('weight', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-weight', '-created'),
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(max_length=16)),
                ('content', jsonfield.fields.JSONField()),
                ('ext_info', jsonfield.fields.JSONField()),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='wechat.MessageHandler')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('rule', jsonfield.fields.JSONField()),
                ('weight', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='wechat.MessageHandler')),
            ],
            options={
                'ordering': ('-weight',),
            },
        ),
        migrations.CreateModel(
            name='WechatApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('desc', models.TextField(blank=True, default='')),
                ('appid', models.CharField(max_length=32, unique=True)),
                ('appsecret', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=32, null=True)),
                ('encoding_aes_key', models.CharField(max_length=43, null=True)),
                ('encoding_mode', models.PositiveSmallIntegerField(choices=[(0, 'plain'), (2, 'safe')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='messagehandler',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_handlers', to='wechat.WechatApp'),
        ),
        migrations.AddField(
            model_name='menu',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='wechat.WechatApp'),
        ),
        migrations.AddField(
            model_name='menu',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_button', to='wechat.Menu'),
        ),
        migrations.AlterIndexTogether(
            name='messagehandler',
            index_together=set([('app', 'weight', 'created')]),
        ),
    ]
