# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

import django
import os


os.environ.setdefault("DJANGO_SETTINGS_MODULE",
                      "wechat_django.tests.settings")

# call django.setup to load installed apps and other stuff
django.setup()

import wechat_django


# -- Project information -----------------------------------------------------

project = 'WeChat-Django'
copyright = '2021, Xavier-Lam'
author = 'Xavier-Lam'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.extlinks',
    "sphinx.ext.intersphinx",
]

extlinks = {
    'source': ('https://github.com/Xavier-Lam/wechat-django/%s', ''),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

html_theme_options = {
    'github_user': 'Xavier-Lam',
    'github_repo': 'wechat-django',
    'github_banner': True,
    'github_type': 'star',
    'show_related': False,
    'note_bg': '#FFF59C'
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Links to Python's docs should reference the most recent version of the 3.x
# branch, which is located at this URL.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'django': ('https://docs.djangoproject.com/en/stable',
               'https://docs.djangoproject.com/en/stable/_objects/'),
    'wechatpy': ('http://docs.wechatpy.org/zh_CN/stable', None)
}

version = wechat_django.__version__
release = wechat_django.__version__