# flake8: noqa
# Generated by Django 2.2.24 on 2021-10-10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The human-readable name of the application', max_length=16, verbose_name='Title')),
                ('name', models.CharField(help_text='The program name of the application', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_\\.]+\\Z'), 'App name can only consist letters, numbers, underscores, hyphens or dots.', 'invalid')], verbose_name='Application name')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Description')),
                ('type', models.IntegerField(choices=[(0, 'Unknown application'), (2, 'Miniprogram'), (1, 'Official account'), (64, 'Web application'), (4, 'WeChat pay'), (16, 'WeChat pay merchant'), (36, 'Hosted WeChat pay'), (8, 'Third party platform'), (34, 'Hosted miniprogram'), (33, 'Hosted official account')], verbose_name='Application type')),
                ('appid', models.SlugField(max_length=32, verbose_name='AppId')),
                ('appsecret', models.BinaryField(blank=True, editable=True, max_length=256, verbose_name='AppSecret')),
                ('configurations', jsonfield.fields.JSONField(default={}, verbose_name='Configurations')),
                ('storage', jsonfield.fields.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wechat_django.Application', verbose_name='Parent application')),
                ('pays', models.ManyToManyField(blank=True, limit_choices_to={'type__in': (4, 36)}, related_name='_application_pays_+', to='wechat_django.Application', verbose_name='WeChat pay')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='OrdinaryApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Ordinary application',
                'verbose_name_plural': 'Ordinary applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.application', models.Model),
        ),
        migrations.CreateModel(
            name='PayApplication',
            fields=[
            ],
            options={
                'verbose_name': 'WeChat pay application',
                'verbose_name_plural': 'WeChat pay applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.application',),
        ),
        migrations.CreateModel(
            name='PayMerchant',
            fields=[
            ],
            options={
                'verbose_name': 'WeChat pay merchant',
                'verbose_name_plural': 'WeChat pay merchants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.application',),
        ),
        migrations.CreateModel(
            name='ThirdPartyPlatform',
            fields=[
            ],
            options={
                'verbose_name': 'Third party platform',
                'verbose_name_plural': 'Third party platforms',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.application', models.Model),
        ),
        migrations.CreateModel(
            name='WeChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.SlugField(max_length=36, verbose_name='openid')),
                ('unionid', models.SlugField(max_length=36, null=True, verbose_name='unionid')),
                ('alias', models.CharField(blank=True, help_text='An alias for user', max_length=16, null=True, verbose_name='Alias')),
                ('nickname', models.CharField(max_length=32, null=True, verbose_name='Nickname')),
                ('avatar_url', models.URLField(max_length=256, null=True, verbose_name='Avatar URL')),
                ('language', models.CharField(max_length=24, null=True, verbose_name='Language')),
                ('ext_info', jsonfield.fields.JSONField(verbose_name='Extension information')),
                ('remark', models.CharField(blank=True, max_length=30, null=True, verbose_name='WeChat remark')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('synchronized_at', models.DateTimeField(default=None, null=True, verbose_name='Last synchronized at')),
                ('refresh_token', models.CharField(max_length=256, null=True, verbose_name='Refresh token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('app', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='wechat_django.Application', verbose_name='WeChat app')),
            ],
            options={
                'verbose_name': 'WeChat user',
                'verbose_name_plural': 'WeChat users',
                'ordering': ('app', '-created_at'),
                'unique_together': {('app', 'openid'), ('unionid', 'app'), ('app', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='AuthorizerApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Authorizer application',
                'verbose_name_plural': 'Authorizer applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.ordinaryapplication', models.Model),
        ),
        migrations.CreateModel(
            name='HostedPayApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Hosted WeChat pay application',
                'verbose_name_plural': 'Hosted WeChat pay applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.payapplication', 'wechat_django.application', models.Model),
        ),
        migrations.CreateModel(
            name='MiniProgramApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Miniprogram application',
                'verbose_name_plural': 'Miniprogram applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.ordinaryapplication', models.Model),
        ),
        migrations.CreateModel(
            name='OfficialAccountApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Official account application',
                'verbose_name_plural': 'Official account applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.ordinaryapplication', models.Model),
        ),
        migrations.CreateModel(
            name='WebApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Web application',
                'verbose_name_plural': 'Web applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.ordinaryapplication', models.Model),
        ),
        migrations.CreateModel(
            name='MiniProgramAuthorizerApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Hosted miniprogram application',
                'verbose_name_plural': 'Hosted miniprogram applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.authorizerapplication', models.Model),
        ),
        migrations.CreateModel(
            name='OfficialAccountAuthorizerApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Hosted official account application',
                'verbose_name_plural': 'Hosted official account applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.authorizerapplication', models.Model),
        ),
    ]
