# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'IMAGE'), ('video', 'VIDEO'), ('voice', 'VOICE')], max_length=5, verbose_name='type')),
                ('media_id', models.CharField(max_length=64, verbose_name='media_id')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='filename')),
                ('url', models.CharField(editable=False, max_length=512, null=True, verbose_name='url')),
                ('update_time', models.IntegerField(editable=False, null=True, verbose_name='update time')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'ordering': ('app', '-update_time'),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名称')),
                ('menuid', models.IntegerField(blank=True, null=True, verbose_name='menuid')),
                ('type', models.CharField(blank=True, choices=[('click', 'CLICK'), ('miniprogram', 'MINIPROGRAM'), ('view', 'VIEW')], max_length=20, null=True, verbose_name='type')),
                ('content', jsonfield.fields.JSONField()),
                ('weight', models.IntegerField(default=0, verbose_name='weight')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('app', '-weight', 'created'),
            },
        ),
        migrations.CreateModel(
            name='MessageHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('src', models.PositiveSmallIntegerField(choices=[(0, 'wechat'), (2, 'self'), (1, 'menu')], default=2, editable=False)),
                ('strategy', models.CharField(choices=[('reply_all', 'reply_all'), ('random_one', 'random_one'), ('none', 'none')], default='random_one', max_length=10, verbose_name='strategy')),
                ('starts', models.DateTimeField(blank=True, null=True, verbose_name='starts')),
                ('ends', models.DateTimeField(blank=True, null=True, verbose_name='ends')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('weight', models.IntegerField(default=0, verbose_name='weight')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'ordering': ('-weight', '-created'),
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(choices=[('custom', 'CUSTOM'), ('forward', 'FORWARD'), ('image', 'IMAGE'), ('img', 'IMG'), ('music', 'MUSIC'), ('news', 'NEWS'), ('text', 'TEXT'), ('video', 'VIDEO'), ('voice', 'VOICE')], max_length=16, verbose_name='type')),
                ('content', jsonfield.fields.JSONField()),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='wechat_django.MessageHandler')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('all', 'ALL'), ('contain', 'CONTAIN'), ('equal', 'EQUAL'), ('event', 'EVENT'), ('eventkey', 'EVENTKEY'), ('msg_type', 'MSGTYPE'), ('regex', 'REGEX')], max_length=16, verbose_name='type')),
                ('rule', jsonfield.fields.JSONField(blank=True)),
                ('weight', models.IntegerField(default=0, verbose_name='weight')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='wechat_django.MessageHandler')),
            ],
            options={
                'ordering': ('-weight',),
            },
        ),
        migrations.CreateModel(
            name='WeChatApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='公众号名称', max_length=16, verbose_name='title')),
                ('name', models.CharField(help_text='公众号唯一标识,可采用微信号', max_length=16, unique=True, verbose_name='名称')),
                ('desc', models.TextField(blank=True, default='', verbose_name='description')),
                ('appid', models.CharField(max_length=32, unique=True, verbose_name='AppId')),
                ('appsecret', models.CharField(max_length=64, verbose_name='AppSecret')),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
                ('encoding_aes_key', models.CharField(blank=True, max_length=43, null=True, verbose_name='EncodingAESKey')),
                ('encoding_mode', models.PositiveSmallIntegerField(choices=[(0, 'plain'), (2, 'safe')], default=0, verbose_name='encoding mode')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='WeChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=36, verbose_name='openid')),
                ('unionid', models.CharField(max_length=36, null=True, verbose_name='unionid')),
                ('nickname', models.CharField(max_length=24, null=True, verbose_name='nickname')),
                ('sex', models.SmallIntegerField(choices=[('2', 'FEMALE'), ('1', 'MALE'), ('0', 'UNKNOWN')], null=True, verbose_name='gender')),
                ('city', models.CharField(max_length=24, null=True, verbose_name='city')),
                ('provice', models.CharField(max_length=24, null=True, verbose_name='province')),
                ('country', models.CharField(max_length=24, null=True, verbose_name='country')),
                ('headimgurl', models.CharField(max_length=256, null=True, verbose_name='avatar')),
                ('subscribe_time', models.IntegerField(null=True, verbose_name='subscribe time')),
                ('subscribe_scene', models.CharField(choices=[('ADD_SCENE_ACCOUNT_MIGRATION', 'ADD_SCENE_ACCOUNT_MIGRATION'), ('ADD_SCENE_OTHERS', 'ADD_SCENE_OTHERS'), ('ADD_SCENE_PAID', 'ADD_SCENE_PAID'), ('ADD_SCENE_PROFILE_CARD', 'ADD_SCENE_PROFILE_CARD'), ('ADD_SCENE_PROFILE_ITEM', 'ADD_SCENE_PROFILE_ITEM'), ('ADD_SCENEPROFILE LINK', 'ADD_SCENE_PROFILE_LINK'), ('ADD_SCENE_QR_CODE', 'ADD_SCENE_QR_CODE'), ('ADD_SCENE_SEARCH', 'ADD_SCENE_SEARCH')], max_length=32, null=True, verbose_name='subscribe scene')),
                ('qr_scene', models.IntegerField(null=True, verbose_name='qr scene')),
                ('qr_scene_str', models.CharField(max_length=64, null=True, verbose_name='qr_scene_str')),
                ('remark', models.TextField(null=True, verbose_name='remark')),
                ('groupid', models.IntegerField(null=True, verbose_name='group id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('app', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='wechat_django.WeChatApp')),
            ],
            options={
                'ordering': ('app', '-created'),
            },
        ),
        migrations.AddField(
            model_name='messagehandler',
            name='app',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='message_handlers', to='wechat_django.WeChatApp'),
        ),
        migrations.AddField(
            model_name='menu',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='wechat_django.WeChatApp'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_button', to='wechat_django.Menu'),
        ),
        migrations.AddField(
            model_name='material',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='wechat_django.WeChatApp'),
        ),
        migrations.AlterUniqueTogether(
            name='wechatuser',
            unique_together=set([('app', 'unionid'), ('app', 'openid')]),
        ),
        migrations.AlterIndexTogether(
            name='messagehandler',
            index_together=set([('app', 'weight', 'created')]),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=set([('app', 'media_id')]),
        ),
    ]
