# Generated by Django 2.2.24 on 2021-10-05
# flake8: noqa

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import wechat_django.models.apps.base
import wechat_django.models.apps.miniprogram
import wechat_django.models.apps.officialaccount


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The human-readable name of the application', max_length=16, verbose_name='Title')),
                ('name', models.CharField(help_text='The program name of the application', max_length=64, unique=True, verbose_name='Application name')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Description')),
                ('type', models.IntegerField(choices=[(0, 'Unknown application'), (2, 'Miniprogram'), (1, 'Official account'), (64, 'Web application'), (4, 'WeChat pay'), (16, 'WeChat pay merchant'), (36, 'Hosted WeChat pay'), (8, 'Third party platform'), (34, 'Hosted miniprogram'), (33, 'Hosted official account')], verbose_name='Application type')),
                ('appid', models.SlugField(max_length=32, verbose_name='AppId')),
                ('appsecret', models.BinaryField(blank=True, editable=True, max_length=256, verbose_name='AppSecret')),
                ('configurations', jsonfield.fields.JSONField(default={}, verbose_name='Configurations')),
                ('storage', jsonfield.fields.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wechat_django.Application', verbose_name='Parent application')),
                ('pays', models.ManyToManyField(blank=True, limit_choices_to={'type__in': (4, 36)}, related_name='_application_pays_+', to='wechat_django.Application', verbose_name='WeChat pay')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='OrdinaryApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Ordinary application',
                'verbose_name_plural': 'Ordinary applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.application',),
        ),
        migrations.CreateModel(
            name='PayApplication',
            fields=[
            ],
            options={
                'verbose_name': 'WeChat pay application',
                'verbose_name_plural': 'WeChat pay applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.application',),
        ),
        migrations.CreateModel(
            name='PayMerchant',
            fields=[
            ],
            options={
                'verbose_name': 'WeChat pay merchant',
                'verbose_name_plural': 'WeChat pay merchants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.application',),
        ),
        migrations.CreateModel(
            name='ThirdPartyPlatform',
            fields=[
            ],
            options={
                'verbose_name': 'Third party platform',
                'verbose_name_plural': 'Third party platforms',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.application',),
        ),
        migrations.CreateModel(
            name='AuthorizerApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Authorizer application',
                'verbose_name_plural': 'Authorizer applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(wechat_django.models.apps.base.HostedApplicationMixin, 'wechat_django.ordinaryapplication'),
        ),
        migrations.CreateModel(
            name='HostedPayApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Hosted WeChat pay application',
                'verbose_name_plural': 'Hosted WeChat pay applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wechat_django.payapplication', wechat_django.models.apps.base.HostedApplicationMixin, 'wechat_django.application'),
        ),
        migrations.CreateModel(
            name='MiniProgramApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Miniprogram application',
                'verbose_name_plural': 'Miniprogram applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(wechat_django.models.apps.miniprogram.MiniProgramApplicationMixin, 'wechat_django.ordinaryapplication'),
        ),
        migrations.CreateModel(
            name='OfficialAccountApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Official account application',
                'verbose_name_plural': 'Official account applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(wechat_django.models.apps.officialaccount.OfficialAccountApplicationMixin, 'wechat_django.ordinaryapplication'),
        ),
        migrations.CreateModel(
            name='MiniProgramAuthorizerApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Hosted miniprogram application',
                'verbose_name_plural': 'Hosted miniprogram applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(wechat_django.models.apps.miniprogram.MiniProgramApplicationMixin, 'wechat_django.authorizerapplication'),
        ),
        migrations.CreateModel(
            name='OfficialAccountAuthorizerApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Hosted official account application',
                'verbose_name_plural': 'Hosted official account applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(wechat_django.models.apps.officialaccount.OfficialAccountApplicationMixin, 'wechat_django.authorizerapplication'),
        ),
    ]
