# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0001_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='language',
            field=models.CharField(max_length=24, null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='wechatuser',
            name='subscribe',
            field=models.NullBooleanField(verbose_name='is subscribed'),
        ),
    ]
