# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0001_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'IMAGE'), ('video', 'VIDEO'), ('voice', 'VOICE')], max_length=5, verbose_name='type')),
                ('media_id', models.CharField(max_length=64, verbose_name='media_id')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='名称')),
                ('url', models.CharField(blank=True, max_length=512, null=True, verbose_name='url')),
                ('update_time', models.CharField(blank=True, max_length=24, null=True, verbose_name='update time')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='ext_info',
        ),
        migrations.AlterField(
            model_name='menu',
            name='menuid',
            field=models.IntegerField(blank=True, null=True, verbose_name='menuid'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=16, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(blank=True, choices=[('click', 'CLICK'), ('miniprogram', 'MINIPROGRAM'), ('view', 'VIEW')], max_length=20, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='msg_type',
            field=models.CharField(choices=[('custom', 'CUSTOM'), ('forward', 'FORWARD'), ('image', 'IMAGE'), ('img', 'IMG'), ('music', 'MUSIC'), ('news', 'NEWS'), ('text', 'TEXT'), ('video', 'VIDEO'), ('voice', 'VOICE')], max_length=16, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='name',
            field=models.CharField(help_text='公众号唯一标识,可采用微信号', max_length=16, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='title',
            field=models.CharField(help_text='公众号名称', max_length=16, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='material',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='wechat_django.WechatApp'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=set([('app', 'media_id')]),
        ),
    ]
