# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0002_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='update_time',
            field=models.IntegerField(editable=False, null=True, verbose_name='update time'),
        ),
        migrations.AlterField(
            model_name='material',
            name='url',
            field=models.CharField(editable=False, max_length=512, null=True, verbose_name='url'),
        ),
    ]
