# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0002_userfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('thumb_media_id', models.CharField(max_length=64, verbose_name='thumb_media_id')),
                ('show_cover_pic', models.BooleanField(default=True, verbose_name='show cover')),
                ('author', models.CharField(blank=True, default='', max_length=24, null=True, verbose_name='author')),
                ('digest', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='digest')),
                ('content', models.TextField(verbose_name='content')),
                ('url', models.CharField(max_length=256, verbose_name='url')),
                ('content_source_url', models.CharField(max_length=256, verbose_name='content source url')),
                ('index', models.PositiveSmallIntegerField(verbose_name='index')),
                ('img_url', models.CharField(max_length=256)),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='updated')),
            ],
            options={
                'ordering': ('material', 'index'),
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('image', 'IMAGE'), ('news', 'NEWS'), ('video', 'VIDEO'), ('voice', 'VOICE')], max_length=5, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='article',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='wechat_django.Material'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('material', 'index')]),
        ),
    ]
