# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0003_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='need_open_comment',
            field=models.NullBooleanField(default=None, verbose_name='need open comment'),
        ),
        migrations.AddField(
            model_name='article',
            name='only_fans_can_comment',
            field=models.NullBooleanField(default=None, verbose_name='need open comment'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumb_url',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
