# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0004_article-fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.BigIntegerField(verbose_name='msgid')),
                ('type', models.CharField(choices=[('event', 'EVENT'), ('image', 'IMAGE'), ('link', 'LINK'), ('location', 'LOCATION'), ('shortvideo', 'SHORTVIDEO'), ('text', 'TEXT'), ('video', 'VIDEO'), ('voice', 'VOICE')], max_length=24, verbose_name='message type')),
                ('content', jsonfield.fields.JSONField()),
                ('createtime', models.IntegerField(verbose_name='createtime')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
        migrations.AddField(
            model_name='messagehandler',
            name='log',
            field=models.BooleanField(default=False, verbose_name='log'),
        ),
        migrations.AddField(
            model_name='wechatapp',
            name='flags',
            field=models.IntegerField(default=0, verbose_name='flags'),
        ),
        migrations.AlterField(
            model_name='messagehandler',
            name='strategy',
            field=models.CharField(choices=[('reply_all', 'reply_all'), ('random_one', 'random_one'), ('none', 'none')], default='reply_all', max_length=10, verbose_name='strategy'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat_django.WeChatApp'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat_django.WeChatUser'),
        ),
    ]
