# Generated by Django 2.1.7 on 2019-05-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0004_templatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(blank=True, help_text='模板标识,用于程序快速查询模板,单app下唯一', max_length=16, null=True, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('app', 'name'), ('app', 'template_id')},
        ),
    ]
