# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-27 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0005_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='remark',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='sex',
            field=models.SmallIntegerField(choices=[(2, 'FEMALE'), (1, 'MALE'), (0, 'UNKNOWN')], null=True, verbose_name='gender'),
        ),
    ]
