# -*- coding: utf-8 -*-
# Generated by Django 2.2 on 2019-12-05 14:29

from django.db import migrations, models
import django.db.models.deletion
import wechat_django.models.app.base


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0005_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniProgramApp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': []
            },
            bases=(wechat_django.models.app.base.ApiClientApp, wechat_django.models.app.base.InteractableApp, 'wechat_django.wechatapp'),
        ),
        migrations.CreateModel(
            name='ServiceApp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': []
            },
            bases=(wechat_django.models.app.base.ApiClientApp, wechat_django.models.app.base.InteractableApp, wechat_django.models.app.base.OAuthApp, 'wechat_django.wechatapp'),
        ),
        migrations.CreateModel(
            name='SubscribeApp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': []
            },
            bases=(wechat_django.models.app.base.ApiClientApp, wechat_django.models.app.base.InteractableApp, 'wechat_django.wechatapp'),
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': []
            },
            bases=(wechat_django.models.app.base.OAuthApp, 'wechat_django.wechatapp'),
        ),
        migrations.AddField(
            model_name='wechatapp',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wechat_django.WeChatApp', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.CharField(choices=[('all', 'ALL'), ('contain', 'CONTAIN'), ('custom', 'CUSTOM'), ('equal', 'EQUAL'), ('event', 'EVENT'), ('eventkey', 'EVENTKEY'), ('msg_type', 'MSGTYPE'), ('regex', 'REGEX')], max_length=16, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='name',
            field=models.CharField(help_text='公众号唯一标识,可采用微信号,设定后不可修改,用于程序辨识', max_length=16, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'MINIPROGRAM'), (0, 'OTHER'), (256, 'PAYPARTNER'), (1, 'SERVICEAPP'), (2, 'SUBSCRIBEAPP'), (4096, 'WEBAPP')], default=1, verbose_name='type'),
        ),
        migrations.AlterUniqueTogether(
            name='wechatapp',
            unique_together={('parent', 'name')},
        ),
    ]
