# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0006_user-comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatapp',
            name='last_sync_openid',
            field=models.CharField(default=None, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='messagehandler',
            name='src',
            field=models.PositiveSmallIntegerField(choices=[(2, 'wechat'), (0, 'self'), (1, 'menu')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='msg_type',
            field=models.CharField(choices=[('custom', 'CUSTOM'), ('forward', 'FORWARD'), ('image', 'IMAGE'), ('music', 'MUSIC'), ('news', 'NEWS'), ('text', 'TEXT'), ('video', 'VIDEO'), ('voice', 'VOICE')], max_length=16, verbose_name='type'),
        ),
        migrations.AlterIndexTogether(
            name='messagelog',
            index_together=set([('app', 'created_at')]),
        ),
    ]
