# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0007_last_sync_openid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagelog',
            options={'ordering': ('app', '-created')},
        ),
        migrations.RenameField(
            model_name='messagelog',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AlterIndexTogether(
            name='messagelog',
            index_together=set([('app', 'created')]),
        ),
    ]
