# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0008_rename created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatapp',
            name='last_sync_openid',
        ),
        migrations.AddField(
            model_name='wechatapp',
            name='configurations',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AddField(
            model_name='wechatapp',
            name='ext_info',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AddField(
            model_name='wechatuser',
            name='synced',
            field=models.DateTimeField(null=True, default=None, verbose_name='synced'),
        ),
    ]
